apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo

helmCharts:
  - name: postgresql
    repo: https://charts.bitnami.com/bitnami
    version: 15.5.20   # pin a version youâ€™re happy with
    releaseName: postgresql
    namespace: demo
    valuesFile: values-postgres.yaml
